require ('configs.keymaps')
require ('configs.settings')

require ('plugins.vim-plug-init')
require ('plugins.setup.nvim-tree')
require ('plugins.setup.tokyonight')
require ('plugins.setup.NeoColumn')
require ('plugins.setup.lualine')
require ('plugins.setup.barbar')
require ('plugins.setup.toggleterm')